### ISSUE TITLE
can you help me sovle this problem?

### ISSUE THREAD

**Issue by panlanlan** [huxiaoman7/mxnet-cnn-plate-recognition#3]
Traceback (most recent call last):
  File "E:/LicensePlate_Recognition/mxnet-cnn-plate-recognition/train.py", line 304, in <module>
    train();
  File "E:/LicensePlate_Recognition/mxnet-cnn-plate-recognition/train.py", line 284, in train
    model = mx.mod.FeedForward(ctx=devs, #使用GPU来跑

- AttributeError: module 'mxnet.module' has no attribute 'FeedForward'

**Comment by huigangwang** [comment]
mxnet没装好
